---
- name: "include vars"
  include_vars: "{{ item }}"
  with_items:
    - "../vars/{{ ansible_distribution }}.yml"
  tags:
    - zabbix-agent
    - zabbix-agent-install

- name: "add repo"
  apt:
    deb: "{{ zabbix_repo }}"
    state: present
  retries: "{{ remote_package_retries }}"
  register: apt_repo_result
  until: apt_repo_result is succeeded
  tags:
    - zabbix-agent
    - zabbix-agent-install

- name: "install"
  apt:
    update_cache: yes
    name: "{{ zabbix_packages }}"
    install_recommends: no
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded
  tags:
    - zabbix-agent
    - zabbix-agent-install

- name: "load config file"
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"
    mode: 0644
  notify: "restart zabbix-agent"
  tags:
    - zabbix-agent
    - zabbix-agent-configure

- name: "allow connections from server"
  ufw:
    rule: allow
    from_ip: "{{ zabbix_Server }}"
  tags:
    - zabbix-agent
    - zabbix-agent-configure

- name: "autostart"
  systemd:
    name: "zabbix-agent"
    enabled: "{{ zabbix_service_enabled }}"
  tags:
    - zabbix-agent
    - zabbix-agent-configure

- meta: flush_handlers
